<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="http://localhost/orabpel/xmllib/obay/Listing_v1_0.xsd"/>
      <rootElement name="listing" namespace="http://schemas.packtpub.com/obay/lst"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="http://localhost/orabpel/xmllib/obay/Listing_v1_0.xsd"/>
      <rootElement name="listingFee" namespace="http://schemas.packtpub.com/obay/lst"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [WED MAR 04 21:12:43 EST 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:auc="http://schemas.packtpub.com/obay/auc"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns0="http://schemas.packtpub.com/obay/lst"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                exclude-result-prefixes="xsl auc ns0 xsd xref xp20 bpws ora ehdr orcl ids hwf">
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:startingPrice) &lt; number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:reservePrice)">
        <xsl:choose>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:reservePrice) &lt; number('1')">
            <ns0:listingFee>0.15</ns0:listingFee>
          </xsl:when>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:reservePrice) &lt; number('5')">
            <ns0:listingFee>0.25</ns0:listingFee>
          </xsl:when>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:reservePrice) &lt; number('15')">
            <ns0:listingFee>0.40</ns0:listingFee>
          </xsl:when>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:reservePrice) &lt; number('30')">
            <ns0:listingFee>0.75</ns0:listingFee>
          </xsl:when>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:reservePrice) &lt; number('100')">
            <ns0:listingFee>1.50</ns0:listingFee>
          </xsl:when>
          <xsl:otherwise>
            <ns0:listingFee>2.00</ns0:listingFee>
          </xsl:otherwise>
        </xsl:choose>
      </xsl:when>
      <xsl:otherwise>
        <xsl:choose>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:startingPrice) &lt; number('1')">
            <ns0:listingFee>0.15</ns0:listingFee>
          </xsl:when>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:startingPrice) &lt; number('5')">
            <ns0:listingFee>0.25</ns0:listingFee>
          </xsl:when>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:startingPrice) &lt; number('15')">
            <ns0:listingFee>0.40</ns0:listingFee>
          </xsl:when>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:startingPrice) &lt; number('30')">
            <ns0:listingFee>0.75</ns0:listingFee>
          </xsl:when>
          <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:listingFormat/ns0:stdAuctionFormat/auc:startingPrice) &lt; number('100')">
            <ns0:listingFee>1.50</ns0:listingFee>
          </xsl:when>
          <xsl:otherwise>
            <ns0:listingFee>2.00</ns0:listingFee>
          </xsl:otherwise>
        </xsl:choose>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
