/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.leaverequest;


public interface LeaveRequest extends com.packtpub.schemas.leaverequest.TLeaveRequest, javax.xml.bind.Element
{
}

