/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.leaverequest;


public class LeaveRequestImpl extends com.packtpub.schemas.leaverequest.TLeaveRequestImpl implements com.packtpub.schemas.leaverequest.LeaveRequest
{
   public LeaveRequestImpl()
   {
      super();
   }

   public LeaveRequestImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("leaveRequest", "http://schemas.packtpub.com/LeaveRequest", ownerDoc); 
   }

   public LeaveRequestImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public LeaveRequestImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
