/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.leaverequest;


public class ObjectFactory 
{
   public com.packtpub.schemas.leaverequest.LeaveRequest createLeaveRequest()
   {
      com.packtpub.schemas.leaverequest.LeaveRequest elem = new com.packtpub.schemas.leaverequest.LeaveRequestImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.leaverequest.TLeaveRequest createTLeaveRequest()
   {
      com.packtpub.schemas.leaverequest.TLeaveRequest elem = new com.packtpub.schemas.leaverequest.TLeaveRequestImpl(ownerDocument);
      return elem;
   }

   public Object newInstance (Class javaContentInterface) throws javax.xml.bind.JAXBException
   {
      Object newInstance = null;
      java.lang.String elemName = javaContentInterface.getName();
      try
      {
         if (elemName.equals("com.packtpub.schemas.leaverequest.LeaveRequest"))
         {
            newInstance = new com.packtpub.schemas.leaverequest.LeaveRequestImpl(ownerDocument);
            return newInstance;
         }
      }
      catch (Exception e)
      {
         throw new javax.xml.bind.JAXBException(e.toString());
      }
      return null;
   }

   public Object getProperty(String name)
   {
      return null;
   }

   public void setProperty(String name, Object value)
   {
   }

   public Object unmarshal(org.w3c.dom.Node node) throws javax.xml.bind.UnmarshalException
   {
      java.lang.String elemName = node.getLocalName();
      try
      {
         if (elemName.equals("leaveRequest"))
         {
            com.packtpub.schemas.leaverequest.LeaveRequest unode = 
                 new com.packtpub.schemas.leaverequest.LeaveRequestImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
      }
      catch (Exception e)
      {
         throw new javax.xml.bind.UnmarshalException(e.toString());
      }
      return null;
   }

   public void setOwnerDocument(oracle.xml.parser.v2.XMLDocument doc)
   {
      ownerDocument = doc;
   }


   public oracle.xml.parser.v2.XMLDocument getOwnerDocument()
   {
      return ownerDocument;
   }

   public Object getSchemaLocation() throws Exception
   {
      return new java.io.File("D:/SoaDev/Chapter07/LeaveApproval/decisionservices/LeaveApprovalDecisionService/war/WEB-INF/wsdl/LeaveRequest.xsd").toURL();
   }

   private oracle.xml.parser.v2.XMLDocument ownerDocument = 
        new oracle.xml.parser.v2.XMLDocument();

}
