/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.leaverequest;


public interface TLeaveRequest
{
   public void setEmployeeId(java.lang.String value);

   public java.lang.String getEmployeeId();

   public void setFullName(java.lang.String value);

   public java.lang.String getFullName();

   public void setStartDate(java.util.Calendar value);

   public java.util.Calendar getStartDate();

   public void setEndDate(java.util.Calendar value);

   public java.util.Calendar getEndDate();

   public void setLeaveType(java.lang.String value);

   public java.lang.String getLeaveType();

   public void setLeaveReason(java.lang.String value);

   public java.lang.String getLeaveReason();

   public void setRequestStatus(java.lang.String value);

   public java.lang.String getRequestStatus();

}

