<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="http://localhost/orabpel/xmllib/obay/Listing_v1_0.xsd"/>
      <rootElement name="listing" namespace="http://schemas.packtpub.com/obay/lst"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="http://localhost/orabpel/xmllib/obay/Listing_v1_0.xsd"/>
      <rootElement name="saleFee" namespace="http://schemas.packtpub.com/obay/lst"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [WED MAR 04 21:45:28 EST 2009]. -->
?>
<xsl:stylesheet version="1.0" xmlns:auc="http://schemas.packtpub.com/obay/auc"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns0="http://schemas.packtpub.com/obay/lst"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                exclude-result-prefixes="xsl auc ns0 xsd xref xp20 bpws ora ehdr orcl ids hwf">
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:currentPrice) &lt;= number('50.00')">
        <ns0:saleFee>
          <xsl:value-of select="format-number(number(/ns0:listing/ns0:listingDetail/ns0:currentPrice) * number('0.05'), '#.00')"/>
        </ns0:saleFee>
      </xsl:when>
      <xsl:when test="number(/ns0:listing/ns0:listingDetail/ns0:currentPrice) &lt;= number('1000.00')">
        <ns0:saleFee>
          <xsl:value-of select="format-number(number(/ns0:listing/ns0:listingDetail/ns0:currentPrice) * number('0.03') + number('1'), '#.00')"/>
        </ns0:saleFee>
      </xsl:when>
      <xsl:otherwise>
        <ns0:saleFee>
          <xsl:value-of select="format-number(number(/ns0:listing/ns0:listingDetail/ns0:currentPrice) * number('0.03') + number('16'), '#.00')"/>
        </ns0:saleFee>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
