<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="AuctionItem.wsdl"/>
      <rootElement name="auctionItem" namespace="http://xmlns.packtpub.com/obay/bp/AuctionItem"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://MSWRIGHT-AU.au.oracle.com:80/orabpel/obay/AuctionProxy/AuctionProxy?wsdl"/>
      <rootElement name="initiateAuction" namespace="http://xmlns.packtpub.com/obay/bs/AuctionProxy"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [SUN FEB 22 12:36:51 EST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:ns1="http://schemas.packtpub.com/obay/cmn"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:pns1="http://xmlns.packtpub.com/AuctionProxy/correlationset"
                xmlns:auc="http://schemas.packtpub.com/obay/auc"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:lst="http://schemas.packtpub.com/obay/lst"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:flt="http://schemas.packtpub.com/obay/flt"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:usr="http://schemas.packtpub.com/obay/usr"
                xmlns:client="http://xmlns.packtpub.com/obay/bp/AuctionItem"
                xmlns:tns="http://xmlns.packtpub.com/obay/bs/AuctionProxy"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                exclude-result-prefixes="xsl plnk ns0 ns1 auc lst flt usr client bpws wsa soap pns1 tns bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <tns:initiateAuction>
      <auc:auctionId>
        <xsl:value-of select="/client:auctionItem/lst:listing/lst:listingId"/>
      </auc:auctionId>
      <auc:auctionType>
        <xsl:value-of select="/client:auctionItem/lst:listing/lst:listingDetail/lst:listingFormat/lst:stdAuctionFormat/auc:auctionType"/>
      </auc:auctionType>
      <auc:startTime>
        <xsl:value-of select="/client:auctionItem/lst:listing/lst:listingDetail/lst:startTime"/>
      </auc:startTime>
      <auc:endTime>
        <xsl:value-of select="xp20:add-dayTimeDuration-to-dateTime(string(/client:auctionItem/lst:listing/lst:listingDetail/lst:startTime),string(/client:auctionItem/lst:listing/lst:listingDetail/lst:duration))"/>
      </auc:endTime>
      <auc:startingPrice>
        <xsl:value-of select="/client:auctionItem/lst:listing/lst:listingDetail/lst:listingFormat/lst:stdAuctionFormat/auc:startingPrice"/>
      </auc:startingPrice>
      <xsl:choose>
        <xsl:when test="/client:auctionItem/lst:listing/lst:listingDetail/lst:listingFormat/lst:stdAuctionFormat/auc:reservePrice > 0.0">
          <auc:reservePrice>
            <xsl:value-of select="/client:auctionItem/lst:listing/lst:listingDetail/lst:listingFormat/lst:stdAuctionFormat/auc:reservePrice"/>
          </auc:reservePrice>
        </xsl:when>
        <xsl:otherwise>
          <auc:reservePrice>
            <xsl:text disable-output-escaping="no">0</xsl:text>
          </auc:reservePrice>
        </xsl:otherwise>
      </xsl:choose>
    </tns:initiateAuction>
  </xsl:template>
</xsl:stylesheet>
