<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="FilePayroll.xsd"/>
      <rootElement name="PayrollList" namespace="http://packt.com/PayrollInputFileService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="PayrollDatabaseService_table.xsd"/>
      <rootElement name="PayrollitemCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PayrollDatabaseService"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [WED JAN 21 14:23:00 GMT 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/PayrollDatabaseService"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://packt.com/PayrollInputFileService"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                exclude-result-prefixes="xsl xsd tns nxsd ns0 bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <ns0:PayrollitemCollection>
      <xsl:for-each select="/tns:PayrollList/tns:Payee">
        <ns0:Payrollitem>
          <ns0:employeeid>
            <xsl:value-of select="tns:EmployeeNo"/>
          </ns0:employeeid>
          <ns0:paymentdate>
            <xsl:value-of select="tns:PayDate"/>
          </ns0:paymentdate>
          <ns0:paymentamount>
            <xsl:value-of select="tns:Amount"/>
          </ns0:paymentamount>
          <ns0:batchid>
            <xsl:value-of select="../tns:Header/tns:Batch"/>
          </ns0:batchid>
          <ns0:batch>
            <ns0:id>
              <xsl:value-of select="../tns:Header/tns:Batch"/>
            </ns0:id>
            <ns0:batchdate>
              <xsl:value-of select="../tns:Header/tns:BatchDate"/>
            </ns0:batchdate>
          </ns0:batch>
          <ns0:employee>
            <ns0:id>
              <xsl:value-of select="tns:EmployeeNo"/>
            </ns0:id>
            <ns0:firstname>
              <xsl:value-of select="tns:FirstName"/>
            </ns0:firstname>
            <ns0:lastname>
              <xsl:value-of select="tns:Lastname"/>
            </ns0:lastname>
          </ns0:employee>
        </ns0:Payrollitem>
      </xsl:for-each>
    </ns0:PayrollitemCollection>
  </xsl:template>
</xsl:stylesheet>
