DROP TABLE OBAY_USER CASCADE CONSTRAINTS;
DROP TABLE LISTING CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE BID CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT_TRANSACTION CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;

DROP SEQUENCE LST_ID_SEQ;
DROP SEQUENCE ACC_TRN_ID_SEQ;
DROP SEQUENCE ACC_ID_SEQ;


CREATE TABLE OBAY_USER
(
  USERID VARCHAR2(20 BYTE) NOT NULL,
  USERSTATUS VARCHAR2(20 BYTE),
  PASSWORD VARCHAR2(20 BYTE),
  TITLE VARCHAR2(20 BYTE),
  FORENAME VARCHAR2(20 BYTE),
  SURNAME VARCHAR2(20 BYTE),
  DOB DATE,
  EMAIL VARCHAR2(20 BYTE),
  ADDRESSLINE1 VARCHAR2(20 BYTE),
  ADDRESSLINE2 VARCHAR2(20 BYTE),
  CITY VARCHAR2(20 BYTE),
  ZIP VARCHAR2(20 BYTE),
  COUNTRY VARCHAR2(20 BYTE),
  STATE VARCHAR2(20 BYTE),
  CARDTYPE VARCHAR2(20 BYTE),
  CARDNUMBER VARCHAR2(20 BYTE),
  CARDHOLDERNAME VARCHAR2(20 BYTE),
  CARDEXPIRYMONTH VARCHAR2(2 BYTE),
  CARDEXPIRYYEAR VARCHAR2(4 BYTE),
  CARDSECURITYNO VARCHAR2(4 BYTE)
, CONSTRAINT OBAY_USER_PK PRIMARY KEY
  (
    USERID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

CREATE TABLE LISTING
(
  LISTING_ID VARCHAR2(20 BYTE) NOT NULL,
  LISTING_STATUS VARCHAR2(20 BYTE) NOT NULL,
  AUCTION_STATUS VARCHAR2(20 BYTE) NOT NULL,
  SELLER_ID VARCHAR2(20 BYTE) NOT NULL,
  CAT_CODE VARCHAR2(20 BYTE) NOT NULL,
  TITLE VARCHAR2(80 BYTE) NOT NULL,
  DESCRIPTION VARCHAR2(2000 BYTE) NOT NULL,
  CONDITION VARCHAR2(20 BYTE) NOT NULL,
  PAYMENT_METHODS VARCHAR2(80 BYTE) NOT NULL,
  LISTING_FORMAT VARCHAR2(20 BYTE) NOT NULL,
  LIST_FEE NUMBER(12, 2),
  SALE_FEE NUMBER(12, 2),
  CURRENT_PRICE NUMBER(12, 2) NOT NULL,
  STARTING_PRICE NUMBER(12, 2) NOT NULL,
  RESERVE_PRICE NUMBER(12, 2),
  START_TIME DATE,
  END_TIME DATE,
  DURATION VARCHAR2(20 BYTE) NOT NULL
, CONSTRAINT ITEM_PK PRIMARY KEY
  (
    LISTING_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

CREATE TABLE CATEGORY
(
  CODE VARCHAR2(8) NOT NULL,
  DESCRIPTION VARCHAR2(32),
  PARENTCODE VARCHAR2(8)
, CONSTRAINT CATEGORY_PK PRIMARY KEY
  (
    CODE
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

CREATE TABLE BID
(
  LISTING_ID VARCHAR2(20 BYTE) NOT NULL,
  BID_ID NUMBER NOT NULL,
  BID_STATUS VARCHAR2(20 BYTE) NOT NULL,
  BIDDER_ID VARCHAR2(20 BYTE) NOT NULL,
  MAX_BID_AMT NUMBER(12, 2) NOT NULL,
  CUR_BID_AMT NUMBER(12, 2) NOT NULL,
  BID_TIME DATE NOT NULL
, CONSTRAINT ITEM_BID_PK1 PRIMARY KEY
  (
    LISTING_ID,
    BID_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

CREATE TABLE ACCOUNT_TRANSACTION
(
  TRN_ID NUMBER NOT NULL,
  ACC_ID NUMBER,
  TRN_DATE DATE,
  TRN_AMOUNT NUMBER(12, 2),
  TRN_DESCRIPTION VARCHAR2(80 BYTE)
, CONSTRAINT ACCOUNT_TRANSACTION_PK PRIMARY KEY
  (
    TRN_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

CREATE TABLE ACCOUNT
(
  ACC_ID NUMBER NOT NULL,
  ACC_TYPE VARCHAR2(3 BYTE) NOT NULL,
  ACC_STATUS VARCHAR2(20 BYTE) NOT NULL,
  BALANCE NUMBER(12, 2) DEFAULT 0 NOT NULL,
  CLIENT_ID VARCHAR2(20 BYTE) NOT NULL,
  CLIENT_TYPE VARCHAR2(20 BYTE) NOT NULL,
  CURRENCY VARCHAR2(3 BYTE) NOT NULL,
  DESCRIPTION VARCHAR2(80 BYTE) NOT NULL
, CONSTRAINT ACCOUNT_PK PRIMARY KEY
  (
    ACC_ID
  )
  ENABLE
)
  TABLESPACE "USERS"
  LOGGING 
  PCTFREE 10
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 64K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
  )
;

ALTER TABLE LISTING
ADD CONSTRAINT LISTING_CATEGORY_FK1 FOREIGN KEY
(
  CAT_CODE
)
REFERENCES CATEGORY
(
  CODE
)
 ENABLE
;

ALTER TABLE CATEGORY
ADD CONSTRAINT CATEGORY_CATEGORY_FK1 FOREIGN KEY
(
  PARENTCODE
)
REFERENCES CATEGORY
(
  CODE
)
 ENABLE
;

ALTER TABLE BID
ADD CONSTRAINT BID_AUCTION_FK1 FOREIGN KEY
(
  LISTING_ID
)
REFERENCES LISTING
(
  LISTING_ID
)
 ENABLE
;

ALTER TABLE ACCOUNT_TRANSACTION
ADD CONSTRAINT ACC_TRN_ACC_FK FOREIGN KEY
(
  ACC_ID
)
REFERENCES ACCOUNT
(
  ACC_ID
)
 ENABLE
;

CREATE SEQUENCE LST_ID_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 CACHE 20;

CREATE SEQUENCE ACC_TRN_ID_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE ACC_ID_SEQ INCREMENT BY 1 START WITH 1000001 MAXVALUE 9999999999 MINVALUE 1000001 CACHE 20;

EXIT;