DROP USER soabook CASCADE;
CREATE USER soabook IDENTIFIED BY soabook;
GRANT CONNECT, RESOURCE TO soabook;

DROP USER obay CASCADE;
CREATE USER obay IDENTIFIED BY obay;
GRANT CONNECT, RESOURCE TO obay;
exit;