/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public class AuctionImpl extends com.packtpub.schemas.obay.auc.TAuctionImpl implements com.packtpub.schemas.obay.auc.Auction
{
   public AuctionImpl()
   {
      super();
   }

   public AuctionImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("auction", "http://schemas.packtpub.com/obay/auc", ownerDoc); 
   }

   public AuctionImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public AuctionImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
