/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public class AuctionItemImpl extends com.packtpub.schemas.obay.auc.TAuctionItemImpl implements com.packtpub.schemas.obay.auc.AuctionItem
{
   public AuctionItemImpl()
   {
      super();
   }

   public AuctionItemImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("auctionItem", "http://schemas.packtpub.com/obay/auc", ownerDoc); 
   }

   public AuctionItemImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public AuctionItemImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
