/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public class BidImpl extends com.packtpub.schemas.obay.auc.TBidImpl implements com.packtpub.schemas.obay.auc.Bid
{
   public BidImpl()
   {
      super();
   }

   public BidImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("bid", "http://schemas.packtpub.com/obay/auc", ownerDoc); 
   }

   public BidImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public BidImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
