/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public class BidNoImpl extends oracle.xml.jaxb.JaxbNode implements com.packtpub.schemas.obay.auc.BidNo
{
   public BidNoImpl()
   {
      super();
   }

   public BidNoImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("bidNo", "http://schemas.packtpub.com/obay/auc", ownerDoc); 
   }

   public BidNoImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public BidNoImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public void setValue(int value)
   {
      super.setJaxbIntValue(value);
   }

   public int getValue()
   {
      return super.getJaxbIntValue();
   }

   static final Object[] _BidNo = 
   {};

   protected Object[] getSchemaObject()
   {
      return _BidNo;
   }

}
