/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public class BidsImpl extends com.packtpub.schemas.obay.auc.TBidsImpl implements com.packtpub.schemas.obay.auc.Bids
{
   public BidsImpl()
   {
      super();
   }

   public BidsImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("bids", "http://schemas.packtpub.com/obay/auc", ownerDoc); 
   }

   public BidsImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public BidsImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
