/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public class ObjectFactory 
{
   public com.packtpub.schemas.obay.auc.BidNo createBidNo(int value)
   {
      com.packtpub.schemas.obay.auc.BidNo elem = new com.packtpub.schemas.obay.auc.BidNoImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.BidNo createBidNo()
   {
      com.packtpub.schemas.obay.auc.BidNo elem = new com.packtpub.schemas.obay.auc.BidNoImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.AuctionItem createAuctionItem()
   {
      com.packtpub.schemas.obay.auc.AuctionItem elem = new com.packtpub.schemas.obay.auc.AuctionItemImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.BidderId createBidderId(java.lang.String value)
   {
      com.packtpub.schemas.obay.auc.BidderId elem = new com.packtpub.schemas.obay.auc.BidderIdImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.BidderId createBidderId()
   {
      com.packtpub.schemas.obay.auc.BidderId elem = new com.packtpub.schemas.obay.auc.BidderIdImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.Bidtime createBidtime(java.util.Calendar value)
   {
      com.packtpub.schemas.obay.auc.Bidtime elem = new com.packtpub.schemas.obay.auc.BidtimeImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.Bidtime createBidtime()
   {
      com.packtpub.schemas.obay.auc.Bidtime elem = new com.packtpub.schemas.obay.auc.BidtimeImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.TAuction createTAuction()
   {
      com.packtpub.schemas.obay.auc.TAuction elem = new com.packtpub.schemas.obay.auc.TAuctionImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.ReservePrice createReservePrice(double value)
   {
      com.packtpub.schemas.obay.auc.ReservePrice elem = new com.packtpub.schemas.obay.auc.ReservePriceImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.ReservePrice createReservePrice()
   {
      com.packtpub.schemas.obay.auc.ReservePrice elem = new com.packtpub.schemas.obay.auc.ReservePriceImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.AuctionId createAuctionId(java.lang.String value)
   {
      com.packtpub.schemas.obay.auc.AuctionId elem = new com.packtpub.schemas.obay.auc.AuctionIdImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.AuctionId createAuctionId()
   {
      com.packtpub.schemas.obay.auc.AuctionId elem = new com.packtpub.schemas.obay.auc.AuctionIdImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.EndTime createEndTime(java.util.Calendar value)
   {
      com.packtpub.schemas.obay.auc.EndTime elem = new com.packtpub.schemas.obay.auc.EndTimeImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.EndTime createEndTime()
   {
      com.packtpub.schemas.obay.auc.EndTime elem = new com.packtpub.schemas.obay.auc.EndTimeImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.AuctionType createAuctionType(java.lang.String value)
   {
      com.packtpub.schemas.obay.auc.AuctionType elem = new com.packtpub.schemas.obay.auc.AuctionTypeImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.AuctionType createAuctionType()
   {
      com.packtpub.schemas.obay.auc.AuctionType elem = new com.packtpub.schemas.obay.auc.AuctionTypeImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.MaxAmount createMaxAmount(double value)
   {
      com.packtpub.schemas.obay.auc.MaxAmount elem = new com.packtpub.schemas.obay.auc.MaxAmountImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.MaxAmount createMaxAmount()
   {
      com.packtpub.schemas.obay.auc.MaxAmount elem = new com.packtpub.schemas.obay.auc.MaxAmountImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.BidId createBidId(java.lang.String value)
   {
      com.packtpub.schemas.obay.auc.BidId elem = new com.packtpub.schemas.obay.auc.BidIdImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.BidId createBidId()
   {
      com.packtpub.schemas.obay.auc.BidId elem = new com.packtpub.schemas.obay.auc.BidIdImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.Bid createBid()
   {
      com.packtpub.schemas.obay.auc.Bid elem = new com.packtpub.schemas.obay.auc.BidImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.AuctionStatus createAuctionStatus(java.lang.String value)
   {
      com.packtpub.schemas.obay.auc.AuctionStatus elem = new com.packtpub.schemas.obay.auc.AuctionStatusImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.AuctionStatus createAuctionStatus()
   {
      com.packtpub.schemas.obay.auc.AuctionStatus elem = new com.packtpub.schemas.obay.auc.AuctionStatusImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.Status createStatus(java.lang.String value)
   {
      com.packtpub.schemas.obay.auc.Status elem = new com.packtpub.schemas.obay.auc.StatusImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.Status createStatus()
   {
      com.packtpub.schemas.obay.auc.Status elem = new com.packtpub.schemas.obay.auc.StatusImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.Auction createAuction()
   {
      com.packtpub.schemas.obay.auc.Auction elem = new com.packtpub.schemas.obay.auc.AuctionImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.StartTime createStartTime(java.util.Calendar value)
   {
      com.packtpub.schemas.obay.auc.StartTime elem = new com.packtpub.schemas.obay.auc.StartTimeImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.StartTime createStartTime()
   {
      com.packtpub.schemas.obay.auc.StartTime elem = new com.packtpub.schemas.obay.auc.StartTimeImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.StartingPrice createStartingPrice(double value)
   {
      com.packtpub.schemas.obay.auc.StartingPrice elem = new com.packtpub.schemas.obay.auc.StartingPriceImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.StartingPrice createStartingPrice()
   {
      com.packtpub.schemas.obay.auc.StartingPrice elem = new com.packtpub.schemas.obay.auc.StartingPriceImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.Bids createBids()
   {
      com.packtpub.schemas.obay.auc.Bids elem = new com.packtpub.schemas.obay.auc.BidsImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.TBid createTBid()
   {
      com.packtpub.schemas.obay.auc.TBid elem = new com.packtpub.schemas.obay.auc.TBidImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.WinningPrice createWinningPrice(double value)
   {
      com.packtpub.schemas.obay.auc.WinningPrice elem = new com.packtpub.schemas.obay.auc.WinningPriceImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.WinningPrice createWinningPrice()
   {
      com.packtpub.schemas.obay.auc.WinningPrice elem = new com.packtpub.schemas.obay.auc.WinningPriceImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.TBids createTBids()
   {
      com.packtpub.schemas.obay.auc.TBids elem = new com.packtpub.schemas.obay.auc.TBidsImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.BidAmount createBidAmount(double value)
   {
      com.packtpub.schemas.obay.auc.BidAmount elem = new com.packtpub.schemas.obay.auc.BidAmountImpl(ownerDocument);
      elem.setValue(value);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.BidAmount createBidAmount()
   {
      com.packtpub.schemas.obay.auc.BidAmount elem = new com.packtpub.schemas.obay.auc.BidAmountImpl(ownerDocument);
      return elem;
   }

   public com.packtpub.schemas.obay.auc.TAuctionItem createTAuctionItem()
   {
      com.packtpub.schemas.obay.auc.TAuctionItem elem = new com.packtpub.schemas.obay.auc.TAuctionItemImpl(ownerDocument);
      return elem;
   }

   public Object newInstance (Class javaContentInterface) throws javax.xml.bind.JAXBException
   {
      Object newInstance = null;
      java.lang.String elemName = javaContentInterface.getName();
      try
      {
         if (elemName.equals("com.packtpub.schemas.obay.auc.BidNo"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.BidNoImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.AuctionItem"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.AuctionItemImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.BidderId"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.BidderIdImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.Bidtime"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.BidtimeImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.ReservePrice"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.ReservePriceImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.AuctionId"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.AuctionIdImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.EndTime"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.EndTimeImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.AuctionType"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.AuctionTypeImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.MaxAmount"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.MaxAmountImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.BidId"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.BidIdImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.Bid"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.BidImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.AuctionStatus"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.AuctionStatusImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.Status"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.StatusImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.Auction"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.AuctionImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.StartTime"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.StartTimeImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.StartingPrice"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.StartingPriceImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.Bids"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.BidsImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.WinningPrice"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.WinningPriceImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("com.packtpub.schemas.obay.auc.BidAmount"))
         {
            newInstance = new com.packtpub.schemas.obay.auc.BidAmountImpl(ownerDocument);
            return newInstance;
         }
      }
      catch (Exception e)
      {
         throw new javax.xml.bind.JAXBException(e.toString());
      }
      return null;
   }

   public Object getProperty(String name)
   {
      return null;
   }

   public void setProperty(String name, Object value)
   {
   }

   public Object unmarshal(org.w3c.dom.Node node) throws javax.xml.bind.UnmarshalException
   {
      java.lang.String elemName = node.getLocalName();
      try
      {
         if (elemName.equals("bidNo"))
         {
            com.packtpub.schemas.obay.auc.BidNo unode = 
                 new com.packtpub.schemas.obay.auc.BidNoImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("auctionItem"))
         {
            com.packtpub.schemas.obay.auc.AuctionItem unode = 
                 new com.packtpub.schemas.obay.auc.AuctionItemImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("bidderId"))
         {
            com.packtpub.schemas.obay.auc.BidderId unode = 
                 new com.packtpub.schemas.obay.auc.BidderIdImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("bidtime"))
         {
            com.packtpub.schemas.obay.auc.Bidtime unode = 
                 new com.packtpub.schemas.obay.auc.BidtimeImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("reservePrice"))
         {
            com.packtpub.schemas.obay.auc.ReservePrice unode = 
                 new com.packtpub.schemas.obay.auc.ReservePriceImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("auctionId"))
         {
            com.packtpub.schemas.obay.auc.AuctionId unode = 
                 new com.packtpub.schemas.obay.auc.AuctionIdImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("endTime"))
         {
            com.packtpub.schemas.obay.auc.EndTime unode = 
                 new com.packtpub.schemas.obay.auc.EndTimeImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("auctionType"))
         {
            com.packtpub.schemas.obay.auc.AuctionType unode = 
                 new com.packtpub.schemas.obay.auc.AuctionTypeImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("maxAmount"))
         {
            com.packtpub.schemas.obay.auc.MaxAmount unode = 
                 new com.packtpub.schemas.obay.auc.MaxAmountImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("bidId"))
         {
            com.packtpub.schemas.obay.auc.BidId unode = 
                 new com.packtpub.schemas.obay.auc.BidIdImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("bid"))
         {
            com.packtpub.schemas.obay.auc.Bid unode = 
                 new com.packtpub.schemas.obay.auc.BidImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("auctionStatus"))
         {
            com.packtpub.schemas.obay.auc.AuctionStatus unode = 
                 new com.packtpub.schemas.obay.auc.AuctionStatusImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("status"))
         {
            com.packtpub.schemas.obay.auc.Status unode = 
                 new com.packtpub.schemas.obay.auc.StatusImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("auction"))
         {
            com.packtpub.schemas.obay.auc.Auction unode = 
                 new com.packtpub.schemas.obay.auc.AuctionImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("startTime"))
         {
            com.packtpub.schemas.obay.auc.StartTime unode = 
                 new com.packtpub.schemas.obay.auc.StartTimeImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("startingPrice"))
         {
            com.packtpub.schemas.obay.auc.StartingPrice unode = 
                 new com.packtpub.schemas.obay.auc.StartingPriceImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("bids"))
         {
            com.packtpub.schemas.obay.auc.Bids unode = 
                 new com.packtpub.schemas.obay.auc.BidsImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("winningPrice"))
         {
            com.packtpub.schemas.obay.auc.WinningPrice unode = 
                 new com.packtpub.schemas.obay.auc.WinningPriceImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("bidAmount"))
         {
            com.packtpub.schemas.obay.auc.BidAmount unode = 
                 new com.packtpub.schemas.obay.auc.BidAmountImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
      }
      catch (Exception e)
      {
         throw new javax.xml.bind.UnmarshalException(e.toString());
      }
      return null;
   }

   public void setOwnerDocument(oracle.xml.parser.v2.XMLDocument doc)
   {
      ownerDocument = doc;
   }


   public oracle.xml.parser.v2.XMLDocument getOwnerDocument()
   {
      return ownerDocument;
   }

   public Object getSchemaLocation() throws Exception
   {
      return new java.io.File("D:/oBay09/Auction/Auction/decisionservices/AuctionDecisionService/war/WEB-INF/wsdl/Auction_v1_0.xsd").toURL();
   }

   private oracle.xml.parser.v2.XMLDocument ownerDocument = 
        new oracle.xml.parser.v2.XMLDocument();

}
