/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public interface Status extends javax.xml.bind.Element
{
   public void setValue(java.lang.String value);

   public java.lang.String getValue();

}

