/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public interface TAuction
{
   public void setAuctionId(java.lang.String value);

   public java.lang.String getAuctionId();

   public void setAuctionStatus(java.lang.String value);

   public java.lang.String getAuctionStatus();

   public void setAuctionItem(com.packtpub.schemas.obay.auc.TAuctionItem value);

   public com.packtpub.schemas.obay.auc.TAuctionItem getAuctionItem();

}

