/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public interface TAuctionItem
{
   public void setAuctionType(java.lang.String value);

   public java.lang.String getAuctionType();

   public void setStartTime(java.util.Calendar value);

   public java.util.Calendar getStartTime();

   public void setEndTime(java.util.Calendar value);

   public java.util.Calendar getEndTime();

   public void setStartingPrice(double value);

   public double getStartingPrice();

   public void setReservePrice(double value);

   public double getReservePrice();

   public void setWinningPrice(double value);

   public double getWinningPrice();

   public void setWinningBid(com.packtpub.schemas.obay.auc.TBid value);

   public com.packtpub.schemas.obay.auc.TBid getWinningBid();

   public void setBidHistory(com.packtpub.schemas.obay.auc.TBids value);

   public com.packtpub.schemas.obay.auc.TBids getBidHistory();

}

