/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public class TAuctionImpl extends oracle.xml.jaxb.JaxbNode implements com.packtpub.schemas.obay.auc.TAuction
{
   public TAuctionImpl()
   {
      super();
   }

   public TAuctionImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("tAuction", "http://schemas.packtpub.com/obay/auc", ownerDoc); 
   }

   public TAuctionImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public TAuctionImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public void setAuctionId(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbElement("auctionId", "http://schemas.packtpub.com/obay/auc", lexval, 0);
   }

   public java.lang.String getAuctionId()
   {
      java.lang.String lexval = super.getJaxbElement("auctionId", "http://schemas.packtpub.com/obay/auc", 0);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void setAuctionStatus(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbElement("auctionStatus", "http://schemas.packtpub.com/obay/auc", lexval, 1);
   }

   public java.lang.String getAuctionStatus()
   {
      java.lang.String lexval = super.getJaxbElement("auctionStatus", "http://schemas.packtpub.com/obay/auc", 1);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void setAuctionItem(com.packtpub.schemas.obay.auc.TAuctionItem value)
   {
      super.setElement("auctionItem", "http://schemas.packtpub.com/obay/auc", (oracle.xml.jaxb.JaxbNode)value, 2);
   }

   public com.packtpub.schemas.obay.auc.TAuctionItem getAuctionItem()
   {
      com.packtpub.schemas.obay.auc.TAuctionItemImpl obj = new com.packtpub.schemas.obay.auc.TAuctionItemImpl(getOwnerDocument());
      return (com.packtpub.schemas.obay.auc.TAuctionItem) super.getElement("auctionItem", "http://schemas.packtpub.com/obay/auc", (oracle.xml.jaxb.JaxbNode)obj, 2);
   }

   public void populateNodeArray(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name, namespace;
      oracle.xml.parser.v2.XMLNode n = (oracle.xml.parser.v2.XMLNode)node.getFirstChild();

      int i = 0;
      while (n != null)
      {
         name = n.getLocalName(); 
         namespace = n.getNamespaceURI();

         if (name == null)
         {
            n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
            i++;
            continue;
         }

         if (namespace == null)
            namespace = "";

         if (name != null)
         {
            if (name.equals("auctionId") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
                  super.setNodeArrayValue(0, n);
            }

         }
         if (name != null)
         {
            if (name.equals("auctionStatus") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
                  super.setNodeArrayValue(1, n);
            }

         }
         if (name != null)
         {
            if (name.equals("auctionItem") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
                  super.setNodeArrayValue(2, n);
            }

         }
         n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
         i++;
      }

      super.populateNodeArray(node);
   }

   static final Object[] _TAuction = 
   {"auctionId", "auctionStatus", "auctionItem"};

   protected Object[] getSchemaObject()
   {
      return _TAuction;
   }

}
