/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public class TBidImpl extends oracle.xml.jaxb.JaxbNode implements com.packtpub.schemas.obay.auc.TBid
{
   public TBidImpl()
   {
      super();
   }

   public TBidImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("tBid", "http://schemas.packtpub.com/obay/auc", ownerDoc); 
   }

   public TBidImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public TBidImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public void setBidNo(int value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printInt(value);
      super.setJaxbElement("bidNo", "http://schemas.packtpub.com/obay/auc", lexval, 0);
   }

   public int getBidNo()
   {
      java.lang.String lexval = super.getJaxbElement("bidNo", "http://schemas.packtpub.com/obay/auc", 0);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseInt(lexval);
   }

   public void setBidderId(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbElement("bidderId", "http://schemas.packtpub.com/obay/auc", lexval, 1);
   }

   public java.lang.String getBidderId()
   {
      java.lang.String lexval = super.getJaxbElement("bidderId", "http://schemas.packtpub.com/obay/auc", 1);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void setBidtime(java.util.Calendar value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printDateTime(value);
      super.setJaxbElement("bidtime", "http://schemas.packtpub.com/obay/auc", lexval, 2);
   }

   public java.util.Calendar getBidtime()
   {
      java.lang.String lexval = super.getJaxbElement("bidtime", "http://schemas.packtpub.com/obay/auc", 2);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseDateTime(lexval);
   }

   public void setMaxAmount(double value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printDouble(value);
      super.setJaxbElement("maxAmount", "http://schemas.packtpub.com/obay/auc", lexval, 3);
   }

   public double getMaxAmount()
   {
      java.lang.String lexval = super.getJaxbElement("maxAmount", "http://schemas.packtpub.com/obay/auc", 3);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseDouble(lexval);
   }

   public void setBidAmount(double value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printDouble(value);
      super.setJaxbElement("bidAmount", "http://schemas.packtpub.com/obay/auc", lexval, 4);
   }

   public double getBidAmount()
   {
      java.lang.String lexval = super.getJaxbElement("bidAmount", "http://schemas.packtpub.com/obay/auc", 4);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseDouble(lexval);
   }

   public void setStatus(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbElement("status", "http://schemas.packtpub.com/obay/auc", lexval, 5);
   }

   public java.lang.String getStatus()
   {
      java.lang.String lexval = super.getJaxbElement("status", "http://schemas.packtpub.com/obay/auc", 5);
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void populateNodeArray(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name, namespace;
      oracle.xml.parser.v2.XMLNode n = (oracle.xml.parser.v2.XMLNode)node.getFirstChild();

      int i = 0;
      while (n != null)
      {
         name = n.getLocalName(); 
         namespace = n.getNamespaceURI();

         if (name == null)
         {
            n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
            i++;
            continue;
         }

         if (namespace == null)
            namespace = "";

         if (name != null)
         {
            if (name.equals("bidNo") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
                  super.setNodeArrayValue(0, n);
            }

         }
         if (name != null)
         {
            if (name.equals("bidderId") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
                  super.setNodeArrayValue(1, n);
            }

         }
         if (name != null)
         {
            if (name.equals("bidtime") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
                  super.setNodeArrayValue(2, n);
            }

         }
         if (name != null)
         {
            if (name.equals("maxAmount") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
                  super.setNodeArrayValue(3, n);
            }

         }
         if (name != null)
         {
            if (name.equals("bidAmount") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
                  super.setNodeArrayValue(4, n);
            }

         }
         if (name != null)
         {
            if (name.equals("status") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
                  super.setNodeArrayValue(5, n);
            }

         }
         n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
         i++;
      }

      super.populateNodeArray(node);
   }

   static final Object[] _TBid = 
   {"bidNo", "bidderId", "bidtime", "maxAmount", "bidAmount", "status"};

   protected Object[] getSchemaObject()
   {
      return _TBid;
   }

}
