/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public class TBidsImpl extends oracle.xml.jaxb.JaxbNode implements com.packtpub.schemas.obay.auc.TBids
{
   public TBidsImpl()
   {
      super();
   }

   public TBidsImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("tBids", "http://schemas.packtpub.com/obay/auc", ownerDoc); 
   }

   public TBidsImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public TBidsImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public java.util.List getBid()
   {
      return (java.util.List)super.getList("bid", "http://schemas.packtpub.com/obay/auc", this, 0);
   }

   public Object createJaxbNode(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name = node.getLocalName();
      java.lang.String namespace = node.getNamespaceURI();
      if (namespace == null)
         namespace = "";

      if (name.equals("bid") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
      {
         com.packtpub.schemas.obay.auc.TBidImpl obj = new com.packtpub.schemas.obay.auc.TBidImpl((oracle.xml.parser.v2.XMLElement)node);
         return obj;
      }

      return null;
   }

   public void populateNodeArray(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name, namespace;
      oracle.xml.parser.v2.XMLNode n = (oracle.xml.parser.v2.XMLNode)node.getFirstChild();

      int i = 0;
      while (n != null)
      {
         name = n.getLocalName(); 
         namespace = n.getNamespaceURI();

         if (name == null)
         {
            n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
            i++;
            continue;
         }

         if (namespace == null)
            namespace = "";

         if (name != null)
         {
            if (name.equals("bid") && namespace.equals("http://schemas.packtpub.com/obay/auc"))
            {
               super.setNodeVectorValue("bid", "http://schemas.packtpub.com/obay/auc", this, 0, n);
            }

         }
         n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
         i++;
      }

      super.populateNodeArray(node);
   }

   static final Object[] _Bid = 
   {};

   static final Object[] _TBids = 
   {_Bid };

   protected Object[] getSchemaObject()
   {
      return _TBids;
   }

}
