/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package com.packtpub.schemas.obay.auc;


public interface TBid
{
   public void setBidNo(int value);

   public int getBidNo();

   public void setBidderId(java.lang.String value);

   public java.lang.String getBidderId();

   public void setBidtime(java.util.Calendar value);

   public java.util.Calendar getBidtime();

   public void setMaxAmount(double value);

   public double getMaxAmount();

   public void setBidAmount(double value);

   public double getBidAmount();

   public void setStatus(java.lang.String value);

   public java.lang.String getStatus();

}

