<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="OrderFulfillment.wsdl"/>
      <rootElement name="fulfillOrder" namespace="http://xmlns.packtpub.com/obay/bp/OrderFulfillment"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="Order_v1_0.xsd"/>
      <rootElement name="order" namespace="http://schemas.packtpub.com/obay/ord"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [TUE MAR 03 09:29:56 EST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:ord="http://schemas.packtpub.com/obay/ord"
                xmlns:cmn="http://schemas.packtpub.com/obay/cmn"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:client="http://xmlns.packtpub.com/obay/bp/OrderFulfillment"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                exclude-result-prefixes="xsl plnk ns0 ord cmn client bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <ord:order>
      <ord:orderNo>
        <xsl:text disable-output-escaping="no">0</xsl:text>
      </ord:orderNo>
      <ord:orderDesc>
        <xsl:value-of select="/client:fulfillOrder/ord:orderDesc"/>
      </ord:orderDesc>
      <ord:itemId>
        <xsl:value-of select="/client:fulfillOrder/ord:itemId"/>
      </ord:itemId>
      <ord:sellerId>
        <xsl:value-of select="/client:fulfillOrder/ord:sellerId"/>
      </ord:sellerId>
      <ord:buyerId>
        <xsl:value-of select="/client:fulfillOrder/ord:buyerId"/>
      </ord:buyerId>
      <ord:orderDetail>
        <ord:orderDate>
          <xsl:value-of select="xp20:current-date()"/>
        </ord:orderDate>
        <ord:orderStatus>
          <xsl:text disable-output-escaping="no">Pre-Shipment</xsl:text>
        </ord:orderStatus>
        <ord:quantity>
          <xsl:value-of select="/client:fulfillOrder/ord:quantity"/>
        </ord:quantity>
        <ord:itemPrice>
          <xsl:value-of select="/client:fulfillOrder/ord:itemPrice"/>
        </ord:itemPrice>
        <ord:subTotal>
          <xsl:value-of select="/client:fulfillOrder/ord:quantity * /client:fulfillOrder/ord:itemPrice"/>
        </ord:subTotal>
        <ord:shippingPrice>
          <xsl:text disable-output-escaping="no">0</xsl:text>
        </ord:shippingPrice>
        <ord:totalPrice>
          <xsl:value-of select="/client:fulfillOrder/ord:itemPrice * /client:fulfillOrder/ord:quantity"/>
        </ord:totalPrice>
        <ord:lastUpdateDate>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </ord:lastUpdateDate>
        <ord:nextAction>
          <xsl:text disable-output-escaping="no">Enter Shipping Details</xsl:text>
        </ord:nextAction>
      </ord:orderDetail>
    </ord:order>
  </xsl:template>
</xsl:stylesheet>
