<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="TaskQueryService.wsdl"/>
      <rootElement name="taskListResponse" namespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="GetPurchasedItems.wsdl"/>
      <rootElement name="getPurchasedItemsResponse" namespace="http://xmlns.packtpub.com/obay/bs/GetPurchasedItems"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [SAT FEB 07 17:57:07 EST 2009]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:query="http://xmlns.oracle.com/bpel/workflow/taskQuery"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
                xmlns:ns0="http://www.w3.org/2001/XMLSchema"
                xmlns:common="http://xmlns.oracle.com/bpel/workflow/common"
                xmlns:cmn="http://schemas.packtpub.com/obay/cmn"
                xmlns:ord="http://schemas.packtpub.com/obay/ord"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:tns="http://xmlns.oracle.com/bpel/workflow/taskQueryService"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:task="http://xmlns.oracle.com/bpel/workflow/task"
                xmlns:client="http://xmlns.packtpub.com/obay/bs/GetPurchasedItems"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                exclude-result-prefixes="xsl query jaxb ns0 common tns task plnk cmn ord client bpws ehdr hwf xp20 xref ora ids orcl">
  <xsl:template match="/">
    <client:getPurchasedItemsResponse>
      <client:purchasedItemsList>
        <xsl:for-each select="/tns:taskListResponse/task:task">
          <ord:orderSummary>
            <ord:orderNo>
              <xsl:value-of select="task:systemAttributes/task:taskNumber"/>
            </ord:orderNo>
            <ord:orderDesc>
              <xsl:value-of select="task:title"/>
            </ord:orderDesc>
            <ord:itemId>
              <xsl:value-of select="task:systemMessageAttributes/task:textAttribute1"/>
            </ord:itemId>
            <ord:sellerId>
              <xsl:value-of select="task:creator"/>
            </ord:sellerId>
            <ord:buyerId>
              <xsl:value-of select="task:systemMessageAttributes/task:textAttribute2"/>
            </ord:buyerId>
            <ord:itemPrice>
              <xsl:value-of select="task:systemMessageAttributes/task:numberAttribute1"/>
            </ord:itemPrice>
            <ord:totalPrice>
              <xsl:value-of select="task:systemMessageAttributes/task:numberAttribute2"/>
            </ord:totalPrice>
            <ord:orderDate>
              <xsl:value-of select="task:systemMessageAttributes/task:dateAttribute1"/>
            </ord:orderDate>
            <ord:orderStatus>
              <xsl:value-of select="task:systemMessageAttributes/task:textAttribute3"/>
            </ord:orderStatus>
            <ord:lastUpdateDate>
              <xsl:value-of select="task:systemAttributes/task:updatedDate"/>
            </ord:lastUpdateDate>
            <ord:nextAction>
              <xsl:value-of select="task:systemMessageAttributes/task:textAttribute4"/>
            </ord:nextAction>
          </ord:orderSummary>
        </xsl:for-each>
      </client:purchasedItemsList>
    </client:getPurchasedItemsResponse>
  </xsl:template>
</xsl:stylesheet>
